---
kind: pipeline
type: docker
name: default

steps:
  - name: sync_push
    image: alpine/git:1.0.7
    environment:
      REPO_REMOTE: https://github.com/fewensa/rtdlib-sys.git
      GITHUB_TOKEN:
        from_secret: GITHUB_TOKEN
    when:
      event:
        - push
    commands:
      - echo "https://$(echo $GITHUB_TOKEN)@github.com" > /root/.git-credentials
      - git config --global credential.helper store
      - git config --global user.email fewensa@protonmail.com
      - git config --global user.name fewensa
      - git remote add github $REPO_REMOTE
      - git push github $DRONE_BRANCH

  - name: sync_tag
    image: alpine/git:1.0.7
    environment:
      REPO_REMOTE: https://github.com/fewensa/rtdlib-sys.git
      GITHUB_TOKEN:
        from_secret: GITHUB_TOKEN
    when:
      event:
        - tag
    commands:
      - echo "https://$(echo $GITHUB_TOKEN)@github.com" > /root/.git-credentials
      - git config --global credential.helper store
      - git config --global user.email fewensa@protonmail.com
      - git config --global user.name fewensa
      - git remote add github $REPO_REMOTE
      - git fetch origin
      - git push github $DRONE_TAG

#---
#kind: pipeline
#name: publish
#
#steps:
#  - name: publish
#    image: rust:1.33-slim
#    volumes:
#      - name: cargo
#        path: /root/.cargo
#    commands:
#      - apt update -y
#      - apt install -y libssl-dev pkg-config
##      - cargo test
#      - sh -f /root/.cargo/credentials
#      - cargo publish
#
#volumes:
#  - name: cargo
#    host:
#      path: /data/mount/cargo
#
#trigger:
#  #  branch:
#  #    - master
#  event:
#    - tag
#
#
#---
#kind: pipeline
#name: build
#
#steps:
#  - name: build
#    image: rust:1.33-slim
#    commands:
#      - apt update -y
#      - apt install -y libssl-dev pkg-config
##      - cargo test
#      - cargo package
#
#trigger:
#  branch:
#    - master
