language: rust

rust:
  - stable

stages:
  - usually
  - name: publish
    if: tag IS present

jobs:
  include:
    - stage: usually
      name: Package rtdlib
      script:
        - cargo package
    - stage: publish
      name: Publish rtdlib to crates.io
      script:
        - cargo login $CRATES_TOKEN
        - cargo publish

